name = "fdzc-ical-gen"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
name = "fdzc-ical-gen"

[env.staging]
name = "fdzc-ical-gen-staging"
